#Application Config
applicationconfig:
  serverid : dev_server_01

#ALS
alsurls:
    #URLS
    baseurl: https://alsprxy231.activity-link.com/kbm/
    hotels: als_get_hotels.cgi   
    locations: als_get_locations.cgi
    transactions: als_get_transaction_types.cgi
    categories: als_get_categories.cgi
    clientChanges: als_get_client_changes.cgi 
    client: 'als_get_client.cgi'   
    rateAdditional: als_get_rates_additional.cgi
    rates: als_get_rates.cgi
    voucher: als_get_vouchers.cgi
    productPricing: als_get_product_pricing.cgi
    insertClient: als_insert_client.cgi
    updateClient: als_update_client.cgi
    
    #Params
    clientParam: 'client='
    ccinfocheckParam: 'ccinfocheck='
    firstParam: '?'
    appendParam: "&"
    categoryGroupParam: 'categorygroup='
    includeDescParam: 'includedesc='
    imageUrlParam:  'imageurl='
    locationParam: 'location='
    productrateParam: 'productrate='
    categoryParam: 'category='
    vendorParam: 'vendor='
    productParam: 'product='
    bookingdateParam: 'bookingdate='
    activitydateParam: 'activitydate='
    dateParam: 'date='
    productinfoParam: 'productinfo='
    contentParam: 'content='
    wholesaleParam: 'wholesale='
    seqParam: 'seq='
    voucherParam: 'voucher='
    issuedParam: 'issued='
    webusercodeParam: 'webusercode='
    lastnameParam: 'lastname='
    emailParam: 'email='
    arrivaldateParam: 'arrivaldate='
    departuredateParam: 'departuredate='
    cellphoneParam: 'cellphone='
    faxphoneParam: 'faxphone='
    homephoneParam: 'homephone='
    clientCodeParam: 'clientcode='
    firstNameParam: 'firstname='
    hotelNameParam: 'hotelname='
    roomNumberParam: 'room='
    workphoneParam: 'workphone='
    otherphoneParam: 'otherphone='
    notesParam: 'notes='
    webreferenceParam: 'webreference='
    hotelParam: 'hotel='